### ISSUE TITLE
Determine Fiscal Year

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/community#27]
Up to us, but needed for 501c3 application. Part 1, Q5

**Comment by joel6653** [comment]
The standard non-calendar-year fiscal-year is July 1–June 30, but the federal government and some local governments use October 1–September 30. But we need to let our own requirements rule, rather than what everyone else is doing. Do we foresee any seasonal events or projects that would become awkward if they were interrupted by the start-stop of a fiscal year? For instance, the Wyoming Community Enrichment Commission that I worked with had to follow the city's fiscal year (July 1), but our concert season was May–September, which was very awkward. (And by awkward, I'm speaking mainly accounting-wise.)

**Comment by jacebrowning** [comment]
It might make sense if we are slightly offset (earlier) from local governments so we can be in full-swing while they are still planning.

**Comment by Allen616** [comment]
City of GR's budget also begins on July 1.

**Comment by Allen616** [comment]
Completed 501c3 application today and chose the standard non-calendar-year fiscal-year, July 1–June 30.
